CREATE TABLE IF NOT EXISTS locations(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  distance INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS clients(
  phone TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  location_id INTEGER,
  FOREIGN KEY(location_id) REFERENCES locations(id)
);